default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: nitanshu

development:
  <<: *default
  database: debt_collection_development

test:
  <<: *default
  database: debt_collection_test
